apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-api-app
  namespace: argocd
spec:
  project: default

  source:
    repoUrl: https://github.com/bconnelly/exp-config.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
