apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-api-app
spec:
  project: default
  source:
    repoURL: https://github.com/bconnelly/exp-config.git
    targetRevision: HEAD
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: basicapi
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true