apiVersion: v1
kind: Service
metadata:
  name: basic-api-service
  namespace: basicapi
spec:
  selector:
    app.kubernetes.io/name: basic-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080