apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-api-deployment
  namespace: basicapi
spec:
  selector:
    matchLabels:
      app: basic-api-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: basic-api-app
    spec:
      containers:
      - name: basic-api-app
        image: bryan949/basic-api:2.0
        ports:
        - containerPort: 80